// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Livraria_controle_emprestimo.DATA.Models
{
    [Table("Livro_Cliente_Emprestimo")]
    public partial class LivroClienteEmprestimo
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        public int Clienteid { get; set; }
        public int Livroid { get; set; }
        [Column("dataEmprestimo", TypeName = "datetime")]
        public DateTime DataEmprestimo { get; set; }
        [Column("dataDevolucao", TypeName = "datetime")]
        public DateTime DataDevolucao { get; set; }

        [ForeignKey("Clienteid")]
        [InverseProperty("LivroClienteEmprestimos")]
        public virtual Cliente Cliente { get; set; }
        [ForeignKey("Livroid")]
        [InverseProperty("LivroClienteEmprestimos")]
        public virtual Livro Livro { get; set; }
    }
}